<a href="https://colab.research.google.com/github/Quang-Trong-Tan-Loc/AI/blob/main/Classify_Crab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn import datasets
from sklearn.linear_model import Perceptron
#thu vien ho tro chia du lieu
from sklearn.model_selection import train_test_split
#do do chinh xac
from sklearn.metrics import accuracy_score
#chuan hoa du lieu
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv('data_crab.csv')
data.head()

sp sex  index   FL   RW    CL    CW   BD
0  B   M      1  8.1  6.7  16.1  19.0  7.0
1  B   M      2  8.8  7.7  18.1  20.8  7.4
2  B   M      3  9.2  7.8  19.0  22.4  7.7
3  B   M      4  9.6  7.9  20.1  23.1  8.2
4  B   M      5  9.8  8.0  20.3  23.0  8.2

In [ ]:
#data[data['sex']!='B'].head(10)

In [19]:
data.replace(to_replace="B",value=0, inplace=True)
data.replace(to_replace="O",value=1, inplace=True)
data.head()

data.replace(to_replace="M",value=0, inplace=True)
data.replace(to_replace="F",value=1, inplace=True)
data.head()

sp  sex  index   FL   RW    CL    CW   BD
0   0    0      1  8.1  6.7  16.1  19.0  7.0
1   0    0      2  8.8  7.7  18.1  20.8  7.4
2   0    0      3  9.2  7.8  19.0  22.4  7.7
3   0    0      4  9.6  7.9  20.1  23.1  8.2
4   0    0      5  9.8  8.0  20.3  23.0  8.2

In [68]:
X = data.drop('sex', axis = True).to_numpy()
y = data ['sex'].to_numpy()
print(X)

[[ 0.   1.   8.1 ... 16.1 19.   7. ]
 [ 0.   2.   8.8 ... 18.1 20.8  7.4]
 [ 0.   3.   9.2 ... 19.  22.4  7.7]
 ...
 [ 1.  48.  21.9 ... 42.6 47.4 19.5]
 [ 1.  49.  22.5 ... 43.  48.7 19.8]
 [ 1.  50.  23.1 ... 46.2 52.5 21.1]]


In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train[:5])
print(y_train[:5])

[[ 1.  46.  21.6 14.8 43.4 48.2 20.1]
 [ 1.  40.  20.1 17.2 39.8 44.1 18.6]
 [ 1.   2.  10.2  8.2 20.2 22.2  9. ]
 [ 0.   8.  10.3  9.5 21.3 24.7  8.9]
 [ 1.   9.  14.7 13.2 29.6 33.4 12.9]]
[0 1 0 1 1]


In [65]:
model=Perceptron(max_iter = 1000, eta0 = 0.05, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
y_pred1 = model.predict(X_train_std)
print(y_pred)
print(y_test)
print("y test",accuracy_score(y_test, y_pred))
print("y train",accuracy_score(y_train, y_pred1))

[1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 0]
[1 0 1 1 1 0 0 1 1 1 1 0 0 1 0 1 1 0 0 0]
y test 0.75
y train 0.8666666666666667
